name: json_serializable  # Can be anything
environment:
  sdk: ^3.5.0

publish_to: none

dev_dependencies:
  dart_flutter_team_lints: ^3.2.0
workspace:
  - _test_yaml
  - checked_yaml
  - example
  - json_annotation
  - json_serializable
  - shared_test
